version: "2.1"
services:
  app:
    build: .
    expose:
      - "5000"
    env_file: .env
    environment:
      - PORT=5000
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=postgresql
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - SESSION_SECRET=$SESSION_SECRET
      - STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
    ports:
      - "5000:5000"
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
